# Generated by Django 5.0 on 2025-02-04 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_school_user'),
        ('questpaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='educator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.educator'),
        ),
    ]
