# Generated by Django 5.0 on 2025-04-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursary',
            name='summary',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
