# Generated by Django 5.0 on 2025-04-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_alter_bursary_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursary',
            name='posted_as',
            field=models.CharField(choices=[('funding', 'Funding'), ('Bursary', 'Bursary'), ('Loan', 'Loan')], max_length=10),
        ),
    ]
