# Generated by Django 4.2.5 on 2024-02-15 10:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Names', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('option_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Where_to_Apply', models.TextField(max_length=255)),
                ('header_image', models.ImageField(upload_to='images/')),
                ('image', models.ImageField(blank=True, default='/static/img/default-user.png', null=True, upload_to='carousel/%Y/%m/%d/')),
                ('application_from', models.CharField(choices=[('school', 'School'), ('individual', 'Individual')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
