# Generated by Django 5.0 on 2025-04-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_school_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(choices=[('DJUNANE', 'DJUNANE'), ('ELIM', 'ELIM'), ('HLALELANI', 'HLALELANI'), ('KETLANI', 'KETLANI'), ('MAHONISI', 'MAHONISI'), ('MASINDI', 'MASINDI'), ('MASUNGULO', 'MASUNGULO'), ('MULWELI', 'MULWELI'), ('MUNZHEDZI', 'MUNZHEDZI'), ('MUTHUHADINI', 'MUTHUHADINI'), ('NKHENSA', 'NKHENSA'), ('RIVONI', 'RIVONI'), ('SHIHLOBYENI', 'SHIHLOBYENI'), ('SHIRLEY', 'SHIRLEY'), ('TRUE_LIFE', 'TRUE_LIFE'), ('TSAKANI', 'TSAKANI'), ('TSHIMONELA', 'TSHIMONELA'), ('TSHIISAPHUNGO', 'TSHIISAPHUNGO'), ('VALDEZIA', 'VALDEZIA'), ('HS_PHILLIPS', 'HS PHILLIPS'), ('LEMANA', 'LEMANA'), ('DR.T.G_Neluvhola_Training_Academy', 'DR.T.G_Neluvhola_Training_Academy'), ('MDR', 'MDR'), ('OZIAS_DAVHANA', 'OZIAS DAVHANA'), ('RIVUBYE', 'RIVUBYE'), ('TSHIAWELO', 'TSHIAWELO'), ('WATERVAL', 'WATERVAL'), ('OTHER', 'OTHER')], default='OTHER', max_length=255),
        ),
    ]
